- README.md
- libraries/compile-examples/Dockerfile
- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/entrypoint.sh
- libraries/spell-check/Dockerfile
- libraries/spell-check/README.md
- libraries/spell-check/action.yml
- libraries/spell-check/entrypoint.sh
Based on discussions in https://github.com/arduino-libraries/ArduinoBLE/pull/34#issuecomment-538345672
PoC tested with:
- https://github.com/arduino-libraries/ArduinoBLE/pull/34
- https://github.com/arduino-libraries/Arduino_OAuth/pulls
> Add initial arduino-libraries actions

- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/entrypoint.sh
In order to compile for 3rd party boards, the Boards Manager URL must be passed to the action.
Demonstration workflow run using the updated compile-examples action:
https://github.com/per1234/Arduino_ConnectionHandler/runs/396674491
> Make compile-examples support boards that require --additional-urls flag

- libraries/compile-examples/entrypoint.sh
Previously, the compile-examples action would only fail if compilation of the last example sketch in `EXAMPLES` failed.
For example, the aentinger/Arduino_MKRMEM run is passing:
https://github.com/aentinger/Arduino_MKRMEM/runs/394646941
but it should not pass, because compilation of the RawFlashAccess example sketch is failing:
https://github.com/aentinger/Arduino_MKRMEM/runs/394646941#step:4:607
```
/github/workspace/examples/RawFlashAccess/RawFlashAccess.ino:33:3: error: 'flash_Id' was not declared in this scope
flash_Id const id = flash.readId();
^~~~~~~~
```
---
Correctly failing aentinger/Arduino_MKRMEM run using the updated action:
https://github.com/per1234/Arduino_MKRMEM/runs/412417957
Correctly passing run using the updated action: …
> Make compile-examples fail if any compilation failed

- libraries/compile-examples/entrypoint.sh
In order to install libraries dependencies with spaces in their names, they must be quoted in the `arduino-cli lib install` command, but this was not previously possible.
Running this workflow with the previous `compile-examples` action:
```yaml
on: push
jobs:
job_1:
runs-on: ubuntu-latest
steps:
- uses: arduino/actions/libraries/compile-examples@master
with:
libraries: MKRNB "Arduino Low Power" "Arduino SigFox for MKRFox1200"
```
Fails to install the libraries with spaces in their names:
https://github.com/per1234/test/runs/469473473#step:3:200
```
arduino-cli lib install MKRNB '"Arduino' Low 'Power"' '"Arduino' SigFox for 'MKRFox1200"'
Error resolving dependencies for "Arduino: looking for library: library "Arduino not found
MKRNB depends on MKRNB@1.3.2
Error resolving dependencies for …
```
> Make compile-examples action support library dependencies with spaces in name

- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
Since it has a default value, the `fqbn` argument is not required.
> Remove incorrect specification that compile-examples' fqbn argument is required

- libraries/compile-examples/Dockerfile
- libraries/compile-examples/entrypoint.sh
- libraries/spell-check/Dockerfile
- libraries/spell-check/entrypoint.sh
- Make libraries actions scripts [ShellCheck ](https://github.com/koalaman/shellcheck)compliant
- Handle failed commands in compile-examples action
- Make variables readonly where possible in libraries actions
- Use long option names in commands of the libraries actions
- Use [shfmt ](https://github.com/mvdan/sh)to format the libraries actions scripts
> Follow best practices in libraries actions scripts

- libraries/spell-check/entrypoint.sh
Quoting the non-array variable caused the arguments to not be recognized by codespell. Making it an array fixes this issue, while still providing support for spaces, etc. in the input.
> Make libraries/spell-check's CODE_SPELL_ARGS variable an array

- libraries/compile-examples/Dockerfile
- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/entrypoint.sh
- libraries/compile-examples/reportsizetrends/reportsizetrends.py
- libraries/compile-examples/reportsizetrends/requirements.txt
- libraries/compile-examples/reportsizetrends/tests/test_reportsizetrends.py
- libraries/report-size-deltas/Dockerfile
- libraries/report-size-deltas/README.md
- libraries/report-size-deltas/action.yml
- libraries/report-size-deltas/reportsizedeltas.py
- libraries/report-size-deltas/tests/data/size-deltas-reports/adafruit-samd-adafruit_feather_m0.json
- libraries/report-size-deltas/tests/data/size-deltas-reports/arduino-samd-mkrgsm1400.json
- libraries/report-size-deltas/tests/data/size-deltas-reports/arduino-samd-mkrnb1500.json
- libraries/report-size-deltas/tests/data/size-deltas-reports/esp8266-esp8266-huzzah.json
- libraries/report-size-deltas/tests/test_reportsizedeltas.py
If the `enable-size-deltas-report` input is set to `true`, on every push to a pull request the change in memory usage of the example sketch specified via the `compile-examples` action's `size-report-sketch` input between the PR's head and base branch will be:
- Shown in the log ([example](https://github.com/per1234/Arduino_ConnectionHandler/runs/500132900#step:4:514)).
- Saved to a JSON formatted file that can be saved to a [workflow artifact](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts) using the [`actions/upload-artifact`](https://github.com/actions/upload-artifact) action ([example](https://github.com/per1234/Arduino_ConnectionHandler/runs/500132864)).
~~NOTE: Due to the current non-reporting of RAM usage, and …
> Add ability for libraries actions to report changes in memory usage

- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/entrypoint.sh
The previous behavior was to recursively search the `examples` folder for sketches and compile all of them.
The `sketch-paths` input added here allows the user to specify specific paths to search for sketches. The default value of the input is `"examples"` so it is completely backwards compatible.
An example of the application for this feature is when sketches are specific to different boards.
Fixes https://github.com/arduino/actions/issues/24 (note that, after discussion on that issue, we concluded that this was an acceptable alternative to an exclude input).
> libraries/compile-examples: allow sketch paths to be specified

- .github/workflows/libraries_report-size-deltas.yml
- libraries/report-size-deltas/tests/test_reportsizedeltas.py
Run the action's unit tests on every PR and push.
I modified one of the unit tests to make it use the absolute path to the test data rather than the relative path. The reason is to avoid having to add an extra line to the workflow file to cd to the test folder.
> libraries/report-size-deltas: add GitHub Actions workflow to run Python unit tests

- .github/workflows/libraries_compile-examples.yml
- libraries/compile-examples/reportsizetrends/.flake8
Use [flake8](https://gitlab.com/pycqa/flake8) to check:
- Formatting compliance with PEP 8 (with the exception of [max line length of 120](https://github.com/arduino/arduino-cli/blob/master/test/.flake8#L3))
- Code style consistency
- Cyclomatic complexity
A configuration file is provided to assist contributors with verifying compliance locally.
---
The linting step of the workflow run is expected to fail due to the Python code currently not being completely compliant with the formatting and style requirements. I will submit additional PRs to fix those issues.
> libraries/compile-examples: lint Python code during CI run

- libraries/compile-examples/entrypoint.sh
Unlike `actions/checkout@v1`, the `actions/checkout@v2` action doesn't fetch the PR base branch. In order to determine the memory usage change, `compile-examples` must checkout the PR base branch. For this reason, before this change the `compile-examples` action with the deltas report feature enabled didn't work with a simple usage of `actions/checkout@v2`.
> libraries/compile-examples: fetch PR base ref before checking it out

- libraries/compile-examples/reportsizetrends/.flake8
- libraries/compile-examples/reportsizetrends/reportsizetrends.py
- libraries/compile-examples/reportsizetrends/tests/test_reportsizetrends.py
- Fix lines exceeding max length
- Fix over-indented continuation lines
- Use line break before binary operators
NOTE: CI continues to fail due to a separate class of flake8 violations. I will fix those issues in a separate PR.
> libraries/compile-examples: Fix flake8 formatting violations in Python code

- README.md
The `setup-arduino-cli` and `setup-protoc` actions have been moved to dedicated repositories. Copies of them are only maintained in this repository to avoid breaking workflows that were configured to use them before the move.
> Note the deprecated actions in the primary readme

- libraries/compile-examples/reportsizetrends/tests/test_reportsizetrends.py
This is required for flake8 compliance.
> libraries/compile-examples: remove the use of star import from Python code

- .github/workflows/libraries_report-size-deltas.yml
- libraries/report-size-deltas/.flake8
- libraries/report-size-deltas/reportsizedeltas.py
- libraries/report-size-deltas/tests/test_reportsizedeltas.py
I have added a flake8 linting step to the workflow and brought the code into compliance.
- Use line break before binary operators
- Fix lines exceeding 120 characters in lenght
- Fix over-indented continuation lines
- Don't use star import 
- Reduce cyclomatic complexity of ReportSizeDeltas.get_json_response()
> Lint the Python code of libraries/report-size-deltas during CI run

- .github/workflows/libraries_compile-examples.yml
- libraries/compile-examples/reportsizetrends/requirements.txt
- libraries/compile-examples/reportsizetrends/tests/pytest.ini
- libraries/compile-examples/reportsizetrends/tests/test_reportsizetrends.py
It makes sense to standardize on a single unit testing framework for all of Arduino's Python code. Since [pytest](https://docs.pytest.org/en/latest/) is already in use in other Arduino projects, that's the one to use here as well.
> libraries/compile-examples: switch to using pytest for unit testing framework

- .github/workflows/libraries_spell-check.yml
- libraries/spell-check/.editorconfig
- libraries/spell-check/entrypoint.sh
- Use [ShellCheck](https://github.com/koalaman/shellcheck) (via [azohra/shell-linter](https://github.com/azohra/shell-linter)) for static analysis.
- Use [shfmt](https://github.com/mvdan/sh) for formatting check.
> libraries/spell-check: add CI workflow for linting of script

- .github/workflows/libraries_compile-examples.yml
- .github/workflows/libraries_report-size-deltas.yml
- .github/workflows/setup-taskflile.yml
Running the workflow is only necessary when files under the action's folder or its workflow configuration itself are modified. For any other changes, the workflow run only slows down the CI results.
Reference:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
> Only run workflows when relevant files are modified

- .github/workflows/libraries_spell-check.yml
- libraries/spell-check/test/test.bats
- libraries/spell-check/test/testdata/codespell-ignore-words-list.txt
- libraries/spell-check/test/testdata/has-misspellings/has-misspellings.txt
- libraries/spell-check/test/testdata/no-misspellings/no-misspellings.txt
Add tests to quickly verify the action is working correctly using the [Bats testing framework](https://github.com/bats-core/bats-core).
The tests will run during the CI build on every change to the relevant files under `libraries/spell-check` or the workflow file itself.
> libraries/spell-check: Add tests

- .github/workflows/libraries_compile-examples.yml
- .github/workflows/libraries_report-size-deltas.yml
Before the latest release of flake8, the configuration file was automatically loaded based on the target path, but that is no longer supported as of the 3.8.0 release:
https://gitlab.com/pycqa/flake8/-/merge_requests/363
> Add --config option to flake8 command in CI workflows

- .github/workflows/spell-check.yml
- etc/codespell-ignore-words-list.txt
- libraries/compile-examples/compilesketches/compilesketches.py
The repository will be checked for commonly misspelled words on every pull request and push.
In the event of false positives, add the word you wish the check to ignore to `etc/codespell-ignore-words-list.txt`. Always use lowercase, as the ignore words list is case-sensitive and the list of commonly misspelled words is in lowercase.
> Add spell-check GitHub Actions workflow

- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
Arbitrary platform dependencies may now be specified via the newly added `platforms` input. This input uses the same YAML-list format and key names as the `libraries` input.
Backwards compatibility is provided by retaining the same behavior of automatically installing the board's platform dependency, as inferred from the fqbn input. The additional Board Manager URL may still be passed via the fqbn input, if desired.
---
- Board Manager
- Local path
- Clone repository
- Archive download
---
The platform under test may now be installed from the local path of the library.
The easiest way to install the platform's tools dependencies is via Board Manager. If the platform from the local path was also installed via Board Manager (as identified by them having the same name value), the Board …
> libraries/compile-examples: allow installation of arbitrary platform dependencies

- libraries/spell-check/README.md
- libraries/spell-check/action.yml
Since this action is only a thin wrapper around [codespell](https://github.com/codespell-project/codespell), it makes sense to add a link to give that excellent project even more recognition.
Users may also find additional information about how the action works in the codespell documentation.
There is absolutely nothing about this action that is specific to libraries. It's just a general check for misspelled words that can be used for any project.
> libraries/spell-check: make miscellaneous improvements to the documentation

- .github/workflows/libraries_compile-examples.yml
- .github/workflows/libraries_report-size-deltas.yml
- .github/workflows/libraries_report-size-trends.yml
- .github/workflows/libraries_spell-check.yml
- libraries/compile-examples/Dockerfile
- libraries/report-size-deltas/Dockerfile
- libraries/report-size-trends/Dockerfile
The `actions/setup-python` action no longer offers the Python 3.8.2 that was pinned in the workflows. This will cause the runs of this repository's CI workflows to error.
For the actions that have a pinned Python version (`compile-examples`, `report-size-deltas`, `report-size-trends`), it makes sense to use the same Python version to run the action as we do to test it, so Python 3.8.3 is now pinned in their CI workflows and Dockerfiles instead of 3.8.2.
The `spell-check` action's Dockerfile just uses whatever version `apt-get install python3` provides, so it makes more sense to configure its CI workflow to just use the default version of Python provided by the `actions/setup-python` action.
---
NOTE: the `libraries/spell-check` workflow is expected to fail due to a release of codespell's …
> Update Python version used in CI workflows and actions

- libraries/spell-check/test/testdata/codespell-ignore-words-list.txt
- libraries/spell-check/test/testdata/has-misspellings/has-misspellings1/has-misspellings.txt
- libraries/spell-check/test/testdata/has-misspellings/has-misspellings2/has-misspellings.txt
- libraries/spell-check/test/testdata/no-misspellings/no-misspellings.txt
"dont" was removed from codespell's commonly misspelled words dictionary in the release that happened a couple days ago (apparently it is used enough as a variable name to warrant being moved to the "code" dictionary, which we don't configure codespell to use). This word was previously used in the tests to trigger the action's misspelled word detection, so its removal broke the tests.
Although it was not necessary, I also switched from using "wont" in the test data as a misspelled word, since this is likely to suffer the same fate eventually (especially since it's a valid word and shouldn't have been in the dictionary to begin with).
---
NOTE: the `libraries/spell-check` workflow is expected to fail due to Python 3.8.2 no longer being available for installation by the …
> libraries/spell-check: update test data to reflect changes to the codespell dictionary

- libraries/compile-examples/README.md
- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
The user may wish to run compilation tests on sketches bundled with installed library dependencies. These are installed to `/home/github/Arduino/libraries`, which is outside the working directory of the action's Docker container.
Use cases:
- Checking impact of changes on libraries that have the library under test as a dependency.
- Checking impact of changes to the platform under test on external libraries.
This required:
- Fixing a bug with the code used to provide user-friendly relative paths in log and report output that made it incompatible with paths outside the working directory provided by the user via the `sketch-paths` input.
- Adding support for `~` in input paths. This allows users to use the familiar universal default user directory (sketchbook) path location (`~/Arduino`) …
> libraries/compile-examples: support sketch paths located outside the workspace

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
Previously, only sketches that use the .ino file extension were recognized.
There are still popular libraries and sketches that use the .pde extension, which are either unmaintained or with maintainers who have no interest in changing the extension ([reference](https://groups.google.com/a/arduino.cc/d/msg/developers/CHHJfU1f_8E/aMo27qy8BgAJ)), so support for .pde is required for this action to be a general purpose tool for compilation testing of all Arduino projects.
> libraries/compile-examples: add support for .pde sketch extension

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
Before this fix, if the FQBN uses a custom board option and the `platform` input is not provided, the action fails:
https://github.com/arduino-libraries/ArduinoBLE/runs/868536766#step:4:12
> libraries/compile-examples: fix automatic platform dependency detection when FQBN uses custom board option

- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
Previously, the action only allowed reporting of memory usage change when the workflow was triggered by a `pull_request` event. This meant the action could only be used to determine the impact of changes proposed via pull requests. This information can also be useful to have either when pushing commits to a feature branch in preparation for a pull request, or for development work flows where pull requests are not always used (as is very common for individual Arduino projects).
This will result in longer push triggered workflow run duration for people with the `enable-size-deltas` input set to `true`, but no other impact. If the previous behavior of only reporting deltas for workflows triggered by a `pull_request` event is desired, this can be achieved using GitHub Actions expression …
> libraries/compile-examples: enable deltas reporting on pushes

- .github/workflows/libraries_compile-examples.yml
- .github/workflows/libraries_report-size-deltas.yml
- .github/workflows/libraries_report-size-trends.yml
- libraries/compile-examples/Dockerfile
- libraries/report-size-deltas/Dockerfile
- libraries/report-size-trends/Dockerfile
The GitHub Actions `actions/setup-python` action no longer offers Python 3.8.3, so it's necessary to update the CI workflow to use Python 3.8.5. It makes sense to use the same Python version for running the action as is used for testing the action, so I also updated the Docker image to python:3.8.5.
> Use Python 3.8.5 for testing and running libraries Python actions

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
In order to access information about private repositories via the GitHub API, a GitHub access token is required.
The only use of the GitHub API by the action is in determining the base ref of the pull request to use for reporting size deltas.
A change was inadvertently made that caused this GitHub API request to be made every time the action was run, even when size deltas reporting was disabled. This resulted in the action failing when triggered from a private repository when the `github-token` input was not provided by the workflow.
> libraries/compile-examples: prevent unnecessary GitHub API request

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
- libraries/report-size-deltas/reportsizedeltas.py
- libraries/report-size-deltas/tests/data/size-deltas-reports-new/arduino-avr-leonardo.json
- libraries/report-size-deltas/tests/data/size-deltas-reports-new/arduino-avr-uno.json
- libraries/report-size-deltas/tests/data/size-deltas-reports-old/arduino-samd-mkrgsm1400.json
- libraries/report-size-deltas/tests/test_reportsizedeltas.py
- libraries/report-size-trends/reportsizetrends/reportsizetrends.py
- libraries/report-size-trends/reportsizetrends/tests/test_reportsizetrends.py
This changes the report generated by the `arduino/actions/libraries/compile-examples` action to use of an array of objects containing compilation data associated with a specific FQBN .
Although the action does not currently support multiple boards per run, this new format makes the report structure able to accomodate data for multiple boards.
As time goes on, it becomes more likely for there to be 3rd party uses of the report, which would be broken by changes to its structure, so it's worth trying to finalize the format now.
Although this is a breaking change to the report structure, the actions that use the report are updated to use the new format, so there is no breakage for the report's intended uses. The `arduino/actions/libraries/report-size-deltas` action is able to detect and …
> Structure sketches report to allow compiling for multiple boards per run

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
- libraries/report-size-deltas/reportsizedeltas.py
- libraries/report-size-deltas/tests/data/size-deltas-reports-new/arduino-avr-leonardo.json
- libraries/report-size-deltas/tests/data/size-deltas-reports-new/arduino-avr-uno.json
- libraries/report-size-deltas/tests/test_reportsizedeltas.py
Previously, only absolute memory usage data was reported.
The memory usage as a percentage of the total available may often be even even more useful. For example, an increase of 10 bytes is much more significant on an ATtiny85 than it is on an ATSAMD21G18.
In order to calculate relative memory usage, it's necessary to know the total available memory. Total available memory is determined in the same manner as the absolute memory usage: by a regular expression on the compilation output. Some platforms are not configured to provide this information. In that case, the maximum and relative memory usage data will be recorded as "N/A" (see the MKR1000 job in the [demonstration PR](https://github.com/per1234/ArduinoIoTCloud/pull/6#issuecomment-684138195)).
---
PR demonstrating the relative memory …
> libraries/compile-examples, libraries/report-size-deltas: Report relative memory usage data

- libraries/compile-examples/README.md
The original design of the action was extremely limiting and so the API was expanded to allow the action to become a flexible, general purpose tool for compilation testing of Arduino sketches.
The old API format continues to be supported, but deprecated. Toward the goal of discouraging the use of the old API in new workflows, the documentation should only mention the new API, or if it is necessary to mention the old API (as is the case with the `libraries` input due to the significant differences in behavior when the new API is used vs. the old), it should be clearly stated that this is deprecated.
> libraries/compile-examples: discourage use of legacy API in documentation

- .github/workflows/libraries_compile-examples.yml
- .github/workflows/libraries_report-size-deltas.yml
- .github/workflows/libraries_report-size-trends.yml
- libraries/compile-examples/codecov.yml
- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/requirements.txt
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
- libraries/report-size-deltas/codecov.yml
- libraries/report-size-deltas/reportsizedeltas.py
- libraries/report-size-deltas/tests/requirements.txt
- libraries/report-size-deltas/tests/test_reportsizedeltas.py
- libraries/report-size-trends/codecov.yml
- libraries/report-size-trends/reportsizetrends/reportsizetrends.py
- libraries/report-size-trends/reportsizetrends/tests/requirements.txt
- libraries/report-size-trends/reportsizetrends/tests/test_reportsizetrends.py
During the CI workflow run testing the code of the libraries actions:
- Generage code coverage report
- Display coverage report in workflow run log
- Upload coverage report to Codecov
Codecov will:
- Comment a coverage report to pull requests
- Cause the check status to be failure when a decrease in coverage was caused
> libraries/*: check code coverage during CI workflow run

- libraries/compile-examples/README.md
- libraries/compile-examples/action.yml
- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
The other two inputs that accept lists: `libraries` and `platforms`, support the value being a string in YAML format, following the precedent established by GitHub for their workflows.
For consistency, it makes sense to also support YAML format for the action's `sketch-paths` input.
---
Demonstration of how the arduino-libraries/ArduinoIoTCloud repository's workflow would look if it used the new format:
https://github.com/per1234/ArduinoIoTCloud/commit/28af61b7efed26115803c565e173713123c221f5#diff-1ab188640fc440a6dba62ef93d03def2
---
The old Bash array style space-separated list format is still supported and the default behavior of using the `examples` folder  remain the same, so this change is backwards compatible.
> libraries/compile-examples: support YAML-format sketch-paths input value

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
Library dependencies of Library Manager sourced libraries (as defined in its [`library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format)) are automatically installed by Arduino CLI. This is a very nice feature, but unfortunately it was causing conflicts when the user explicitly defined a library dependency for libraries that were also automatically installed by the Arduino Library Manager dependency system.
---
There were several types of conflict:
When an explicit dependency definition for a Library Manager sourced library dependency with an earlier verison was also an automated Library Manager dependency:
```yaml
libraries: |
- name: Arduino_ConnectionHandler
version: 0.4.8
- name: ArduinoIoTCloud
```
Library …
> libraries/compile-examples: fix conflict between explicit and automated library dependency installation

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
This PR adds support for submodules in two ways:
- In dependencies installed from repository sources
- In the checkouts done to the repository under test when deltas reporting is enabled
> libraries/compile-examples: add support for submodules

- libraries/compile-examples/compilesketches/compilesketches.py
- libraries/compile-examples/compilesketches/tests/test_compilesketches.py
Previously, the shared function used to install dependencies from local paths used copy instead of symlinks.
The switch to using copy for everything was done for a couple of reasons:
- Some functions were already using copy/move to install because they worked from temporary folders that only had a lifetime within the function call
- Use of symlinks on Windows requires the script to be run as administrator, which makes it less friendly to contributors or users running the script locally who are using Windows
However, the previous symlinks were essential for the deltas feature to work for libraries or platforms under test because these are installed to a different location than the repository that is checked out to the delta base and head refs.
When the project under test is a sketch, …
> libraries/compile-examples: install dependencies from local path using symlinks

- setup-taskfile/action.yml
This PR tries to fix the warning:
```
Warning: Unexpected input(s) 'repo-token', valid inputs are ['version']
```
The problem comes from `repo-token` not being defined in the `action.yml`
[This comment](https://github.community/t/issue-not-created-and-action-shows-unexpected-input-repo-token-valid-inputs-are-joke-issue-title-warning/116568/3) helped me solve the issue
> Fix unexpected input warning

- setup-taskfile/action.yml
Hey there, Task author here.
I noticed that this action seems to be installing an old release by default. Checking the code, it was clear why.
Please note that I haven't really tested this change. If someone with more knowledge of GitHub Actions thinks this can break stuff for someone, please let me know.
> Task: Install v3.x.x by default

- setup-taskfile/__tests__/main.test.ts
- setup-taskfile/lib/installer.js
- setup-taskfile/src/installer.ts
As discussed in #65 we could improve in `setup-taskfile` GitHub API usage by removing querying the APIs each time the action is used.
This PR allow skipping querying the GitHub APIs if a valid `semver` is specified in the `version` action input parameter.
> GitHub api rate limiting improvements

- README.md
- setup-taskfile/README.md
- setup-taskfile/lib/main.js
- setup-taskfile/src/main.ts
The `setup-taskfile` action has been moved to a dedicated repository, where it is actively maintained:
https://github.com/arduino/setup-task
This fact is now communicated to visitors and users by:
- Notes in top level readme
- Notes in action level readmes
- Warning printed in workflow run summary and logs
> Deprecate unmaintained setup-taskfile action copy
